apiVersion: v1
kind: Service
metadata:
  name: demo-ci-cd
  labels:
    app: demo-ci-cd
spec:
  type: NodePort
  selector:
    app: demo-ci-cd
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
